# Generated by Django 4.2.9 on 2024-01-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_people_delete_saves'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Saves',
        ),
    ]
